# Generated by Django 5.2.16 on 2026-08-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('default_language', models.CharField(choices=[('es-ES', 'Español'), ('en', 'Inglés')], default='es-ES', max_length=5, verbose_name='idioma predeterminado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración de instalación',
                'verbose_name_plural': 'configuración de instalación',
            },
        ),
    ]
