# Generated by Django 5.2.16 on 2026-08-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installationsettings',
            options={'verbose_name': 'installation settings', 'verbose_name_plural': 'installation settings'},
        ),
        migrations.AlterField(
            model_name='installationsettings',
            name='default_language',
            field=models.CharField(choices=[('es-ES', 'Spanish'), ('en', 'English')], default='es-ES', max_length=5, verbose_name='default language'),
        ),
    ]
