# Generated by Django 5.2.16 on 2026-08-19 14:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_installationsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationsettings',
            name='default_crowdfunding_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, verbose_name='default crowdfunding tax rate'),
        ),
    ]
