# Generated by Django 5.2.16 on 2026-07-22 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('fund', 'Fondo'), ('stock', 'Acción'), ('etf', 'ETF'), ('crypto', 'Crypto')], max_length=12)),
                ('name', models.CharField(max_length=240)),
                ('base_currency', models.CharField(blank=True, max_length=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StockSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('ratio', models.DecimalField(decimal_places=12, max_digits=24)),
                ('source', models.CharField(default='manual', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-effective_date',),
            },
        ),
        migrations.CreateModel(
            name='InstrumentIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme', models.CharField(choices=[('isin', 'ISIN'), ('yahoo', 'Yahoo'), ('crypto_symbol', 'Símbolo crypto'), ('kraken', 'Kraken'), ('other', 'Otro')], max_length=20)),
                ('value', models.CharField(max_length=120)),
                ('venue', models.CharField(blank=True, max_length=40)),
                ('is_primary', models.BooleanField(default=False)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='market_data.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quoted_at', models.DateTimeField()),
                ('granularity', models.CharField(choices=[('spot', 'Spot'), ('day', 'Día'), ('week', 'Semana'), ('month', 'Mes')], max_length=8)),
                ('open', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('close', models.DecimalField(decimal_places=10, max_digits=24)),
                ('currency', models.CharField(max_length=4)),
                ('price_eur', models.DecimalField(decimal_places=10, max_digits=24)),
                ('fx_rate_to_eur', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('source', models.CharField(max_length=40)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market_data.instrument')),
            ],
            options={
                'ordering': ('-quoted_at',),
            },
        ),
    ]
