# Generated by Django 5.2.16 on 2026-07-22 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksplit',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_splits_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocksplit',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='market_data.instrument'),
        ),
        migrations.AddField(
            model_name='stocksplit',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_splits', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='instrumentidentifier',
            index=models.Index(fields=['scheme', 'value'], name='market_data_scheme_3295c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='instrumentidentifier',
            constraint=models.UniqueConstraint(fields=('scheme', 'value', 'venue'), name='instrument_identifier_unique'),
        ),
        migrations.AddConstraint(
            model_name='instrumentidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('instrument', 'scheme'), name='instrument_primary_identifier_unique'),
        ),
        migrations.AddIndex(
            model_name='marketprice',
            index=models.Index(fields=['instrument', '-quoted_at'], name='market_data_instrum_6b62b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketprice',
            constraint=models.UniqueConstraint(fields=('instrument', 'quoted_at', 'granularity', 'source'), name='market_price_unique'),
        ),
        migrations.AddConstraint(
            model_name='marketprice',
            constraint=models.CheckConstraint(condition=models.Q(('close__gte', 0)), name='market_price_close_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='marketprice',
            constraint=models.CheckConstraint(condition=models.Q(('price_eur__gte', 0)), name='market_price_eur_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stocksplit',
            constraint=models.UniqueConstraint(fields=('workspace', 'instrument', 'effective_date'), name='stock_split_unique'),
        ),
        migrations.AddConstraint(
            model_name='stocksplit',
            constraint=models.CheckConstraint(condition=models.Q(('ratio__gt', 0)), name='stock_split_ratio_positive'),
        ),
    ]
