# Generated by Django 5.2.16 on 2026-07-28 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_instrument_metadata'),
        ('workspaces', '0002_workspaceinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceInstrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_links', to='market_data.instrument')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_links', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('instrument__name',),
                'constraints': [models.UniqueConstraint(fields=('workspace', 'instrument'), name='workspace_instrument_unique')],
            },
        ),
    ]
