# Generated by Django 5.2.16 on 2026-08-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_workspaceinstrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='kind',
            field=models.CharField(choices=[('fund', 'Fund'), ('stock', 'Stock'), ('etf', 'ETF'), ('crypto', 'Crypto')], max_length=12),
        ),
        migrations.AlterField(
            model_name='instrumentidentifier',
            name='scheme',
            field=models.CharField(choices=[('isin', 'ISIN'), ('yahoo', 'Yahoo'), ('crypto_symbol', 'Crypto symbol'), ('kraken', 'Kraken'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='granularity',
            field=models.CharField(choices=[('spot', 'Spot'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=8),
        ),
    ]
