# Generated by Django 5.2.16 on 2026-08-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('es-ES', 'Español'), ('en', 'Inglés')], default='', help_text='Déjalo vacío para usar el idioma predeterminado de la instalación.', max_length=5, verbose_name='idioma preferido'),
        ),
    ]
