# Generated by Django 5.2.16 on 2026-07-22 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('imports', '0001_initial'),
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=180, null=True)),
                ('trade_date', models.DateField()),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('operation_type', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venta'), ('transfer_in', 'Traspaso entrante'), ('transfer_out', 'Traspaso saliente')], max_length=16)),
                ('cash_flow_type', models.CharField(choices=[('contribution', 'Aportación'), ('withdrawal', 'Retirada'), ('internal', 'Interno'), ('none', 'Ninguno')], default='none', max_length=16)),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=36)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('net_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('market', models.CharField(blank=True, max_length=80)),
                ('is_saveback', models.BooleanField(default=False)),
                ('provider_operation_type', models.CharField(blank=True, max_length=80)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.account')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='imports.importbatch')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='market_data.instrument')),
            ],
            options={
                'ordering': ('-trade_date', '-created_at'),
                'indexes': [models.Index(fields=['account', '-trade_date'], name='transaction_account_f7c169_idx'), models.Index(fields=['instrument', '-trade_date'], name='transaction_instrum_6e0b31_idx'), models.Index(fields=['import_batch'], name='transaction_import__db8771_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('account', 'external_id'), name='transaction_external_id_unique'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transaction_quantity_positive'), models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='transaction_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('fee__gte', 0)), name='transaction_fee_nonnegative')],
            },
        ),
    ]
