# Generated by Django 5.2.16 on 2026-08-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cash_flow_type',
            field=models.CharField(choices=[('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('internal', 'Internal'), ('none', 'None')], default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('transfer_in', 'Incoming transfer'), ('transfer_out', 'Outgoing transfer')], max_length=16),
        ),
    ]
