# Generated by Django 5.2.16 on 2026-07-22 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_label', models.CharField(blank=True, max_length=160)),
                ('name', models.CharField(max_length=200)),
                ('asset_class', models.CharField(max_length=80)),
                ('subtype', models.CharField(blank=True, max_length=120)),
                ('value', models.DecimalField(decimal_places=8, max_digits=24)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('valued_at', models.DateField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_assets', to='accounts.financialprovider')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
