# Generated by Django 5.2.16 on 2026-07-22 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_label', models.CharField(blank=True, max_length=160)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('savings', 'Ahorro'), ('manual_investment', 'Inversión manual'), ('funds', 'Fondos'), ('stocks', 'Acciones'), ('crypto', 'Crypto')], max_length=24)),
                ('subtype', models.CharField(blank=True, max_length=80)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('external_id', models.CharField(blank=True, max_length=180, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=24)),
                ('contribution', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('earnings', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='FinancialProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('provider_type', models.CharField(choices=[('bank', 'Banco'), ('broker', 'Broker'), ('exchange', 'Exchange'), ('real_estate', 'Inmobiliario'), ('other', 'Otro')], max_length=20)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('auth_type', models.CharField(choices=[('oauth', 'OAuth'), ('api_key', 'Clave API'), ('credentials', 'Credenciales'), ('none', 'Sin autenticación')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('expired', 'Caducada'), ('revoked', 'Revocada'), ('error', 'Error')], default='pending', max_length=20)),
                ('secret_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_payload', models.BinaryField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
