# Generated by Django 5.2.16 on 2026-07-22 22:02

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='accountsnapshot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='accounts.account'),
        ),
        migrations.AddConstraint(
            model_name='financialprovider',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='provider_name_ci_unique'),
        ),
        migrations.AddField(
            model_name='account',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.financialprovider'),
        ),
        migrations.AddField(
            model_name='providerconnection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_connections_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerconnection',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='accounts.financialprovider'),
        ),
        migrations.AddField(
            model_name='providerconnection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='account',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.providerconnection'),
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['account', '-date'], name='accounts_ac_account_b06ec9_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountsnapshot',
            constraint=models.UniqueConstraint(fields=('account', 'date'), name='account_snapshot_unique'),
        ),
        migrations.AddConstraint(
            model_name='providerconnection',
            constraint=models.CheckConstraint(condition=models.Q(('auth_type', 'none'), ('secret_reference__isnull', False), ('encrypted_payload__isnull', False), _connector='OR'), name='connection_requires_secret'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['workspace', 'kind', 'archived_at'], name='accounts_ac_workspa_bc1d17_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('workspace', 'provider', 'external_id'), name='account_external_id_unique'),
        ),
    ]
