# Generated by Django 5.2.16 on 2026-08-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_importer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kind',
            field=models.CharField(choices=[('savings', 'Savings'), ('manual_investment', 'Manual investment'), ('funds', 'Funds'), ('stocks', 'Stocks'), ('crypto', 'Crypto')], max_length=24),
        ),
        migrations.AlterField(
            model_name='financialprovider',
            name='provider_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('broker', 'Broker'), ('exchange', 'Exchange'), ('real_estate', 'Real estate'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='providerconnection',
            name='auth_type',
            field=models.CharField(choices=[('oauth', 'OAuth'), ('api_key', 'API key'), ('credentials', 'Credentials'), ('none', 'No authentication')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='providerconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
