# Generated by Django 5.2.16 on 2026-07-22 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateCashFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('flow_type', models.CharField(choices=[('contribution', 'Aportación'), ('reinvestment', 'Reinversión'), ('capital_return', 'Devolución de capital'), ('profit', 'Beneficio')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('is_external', models.BooleanField(default=False)),
                ('source_note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('effective_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RealEstateInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_label', models.CharField(blank=True, max_length=160)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('defaulted', 'Impagada'), ('cancelled', 'Cancelada')], default='active', max_length=12)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('expected_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('expected_irr', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('expected_term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=160)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_investments', to='accounts.financialprovider')),
            ],
            options={
                'ordering': ('-start_date', 'name'),
            },
        ),
    ]
