# Generated by Django 5.2.16 on 2026-07-22 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateinvestment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_investments', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='realestatecashflow',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_flows', to='real_estate.realestateinvestment'),
        ),
        migrations.AddConstraint(
            model_name='realestatecashflow',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='real_estate_cash_flow_nonnegative'),
        ),
    ]
