# Generated by Django 5.2.16 on 2026-08-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_realestateinvestment_legacy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatecashflow',
            name='flow_type',
            field=models.CharField(choices=[('contribution', 'Contribution'), ('reinvestment', 'Reinvestment'), ('capital_return', 'Capital return'), ('profit', 'Profit')], max_length=16),
        ),
        migrations.AlterField(
            model_name='realestateinvestment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='active', max_length=12),
        ),
    ]
