# Generated by Django 5.2.16 on 2026-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_real_estate_reporting_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateinvestment',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional withholding tax rate override percentage.', max_digits=5, null=True),
        ),
    ]
