# Generated by Django 5.2.16 on 2026-08-20

from decimal import Decimal

from django.db import migrations, models


def backfill_profit_withholding_rates(apps, schema_editor):
    InstallationSettings = apps.get_model("common", "InstallationSettings")
    RealEstateCashFlow = apps.get_model("real_estate", "RealEstateCashFlow")
    default_rate = (
        InstallationSettings.objects.filter(pk=1)
        .values_list("default_crowdfunding_tax_rate", flat=True)
        .first()
    )
    if default_rate is None:
        default_rate = Decimal("19.00")

    for flow in RealEstateCashFlow.objects.filter(flow_type="profit").select_related("investment"):
        flow.withholding_rate = (
            flow.investment.tax_rate
            if flow.investment.tax_rate is not None
            else default_rate
        )
        flow.save(update_fields=("withholding_rate",))


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_installationsettings_default_crowdfunding_tax_rate"),
        ("real_estate", "0006_realestateinvestment_tax_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestatecashflow",
            name="withholding_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Withholding rate applied to this profit flow.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_profit_withholding_rates, migrations.RunPython.noop),
    ]
