# Generated by Django 5.2.16 on 2026-08-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspaceinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
        migrations.AlterField(
            model_name='workspacemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
    ]
