from django.urls import path

from .account_views import (
    crypto_account,
    crypto_accounts,
    fund_account,
    fund_accounts,
    investment_account,
    investment_accounts,
    investment_history,
    investment_snapshot_detail,
    savings_account,
    savings_accounts,
    savings_history,
    savings_snapshot_detail,
    stock_account,
    stock_accounts,
)
from .admin_users import user_detail, users
from .analysis_views import crypto_analysis, fund_analysis, portfolio_analysis, stock_analysis
from .auth import (
    accept_invitation,
    change_password,
    csrf,
    invite,
    login_view,
    logout_view,
    me,
    password_reset_confirm,
    password_reset_request,
    select_workspace,
    update_account,
    update_installation_preferences,
    update_preferences,
)
from .budget_views import budget
from .fx_views import fetch_fx_rates, fx_convert, fx_rate_chart, fx_rate_detail, fx_rates
from .instrument_views import crypto_detail, cryptos, fund_detail, funds, stock_detail, stocks
from .market_views import (
    crypto_chart,
    crypto_prices,
    fetch_crypto_prices,
    fetch_fund_prices,
    fetch_stock_prices,
    fund_chart,
    fund_price_detail,
    fund_prices,
    stock_chart,
    stock_price_detail,
    stock_prices,
    stock_split_detail,
    stock_splits,
)
from .overview_views import net_worth_history, summary
from .performance_views import investment_performance_view
from .portfolio_views import portfolio, portfolio_detail
from .privacy import audit_events, delete_account, export_account
from .real_estate_views import real_estate, real_estate_detail
from .transaction_views import (
    crypto_orders,
    crypto_transaction_detail,
    fund_transaction_detail,
    orders,
    stock_orders,
    stock_transaction_detail,
)
from .uploads import (
    catalog,
    upload_for_account,
    upload_funds,
    upload_kraken_pro,
    upload_trade_republic,
)

urlpatterns = [
    path("auth/csrf", csrf),
    path("auth/login", login_view),
    path("auth/logout", logout_view),
    path("auth/me", me),
    path("auth/preferences", update_preferences),
    path("auth/account", update_account),
    path("auth/password", change_password),
    path("auth/password-reset", password_reset_request),
    path("auth/password-reset/confirm", password_reset_confirm),
    path("administration/users", users),
    path("administration/users/<uuid:user_id>", user_detail),
    path("installation/preferences", update_installation_preferences),
    path("workspaces/current", select_workspace),
    path("workspaces/invitations", invite),
    path("workspaces/invitations/accept", accept_invitation),
    path("account/export", export_account),
    path("account", delete_account),
    path("audit-events", audit_events),
    path("importers", catalog),
    path("account-imports/<str:kind>/<uuid:account_id>", upload_for_account),
    path("summary", summary),
    path("net-worth-history", net_worth_history),
    path("savings/accounts", savings_accounts),
    path("savings/accounts/<uuid:account_id>", savings_account),
    path("savings/history", savings_history),
    path(
        "savings/history/<uuid:account_id>/<str:value_date>",
        savings_snapshot_detail,
    ),
    path("investments/accounts", investment_accounts),
    path("investments/accounts/<uuid:account_id>", investment_account),
    path("investments/history", investment_history),
    path(
        "investments/history/<uuid:account_id>/<str:value_date>",
        investment_snapshot_detail,
    ),
    path("portfolio", portfolio),
    path("portfolio/<uuid:asset_id>", portfolio_detail),
    path("portfolio-analysis", portfolio_analysis),
    path("real-estate", real_estate),
    path("real-estate/<uuid:investment_id>", real_estate_detail),
    path("budget", budget),
    path("fund-accounts", fund_accounts),
    path("fund-accounts/<uuid:account_id>", fund_account),
    path("stock-accounts", stock_accounts),
    path("stock-accounts/<uuid:account_id>", stock_account),
    path("crypto-accounts", crypto_accounts),
    path("crypto-accounts/<uuid:account_id>", crypto_account),
    path("funds", funds),
    path("funds/<uuid:instrument_id>", fund_detail),
    path("stocks", stocks),
    path("stocks/<uuid:instrument_id>", stock_detail),
    path("cryptos", cryptos),
    path("cryptos/<uuid:instrument_id>", crypto_detail),
    path("orders", orders),
    path("orders/<uuid:transaction_id>", fund_transaction_detail),
    path("fund-orders/upload", upload_funds),
    path("fund-prices/fetch", fetch_fund_prices),
    path("stock-orders", stock_orders),
    path("stock-orders/upload-tr", upload_trade_republic),
    path("stock-orders/<uuid:transaction_id>", stock_transaction_detail),
    path("crypto-orders", crypto_orders),
    path("crypto-orders/upload-kraken-pro", upload_kraken_pro),
    path("crypto-orders/upload-kraken", upload_kraken_pro),
    path("crypto-orders/<uuid:transaction_id>", crypto_transaction_detail),
    path("fund-prices", fund_prices),
    path("fund-prices/<uuid:instrument_id>", fund_price_detail),
    path("stock-prices/fetch", fetch_stock_prices),
    path("stock-prices", stock_prices),
    path("stock-prices/<uuid:instrument_id>", stock_price_detail),
    path("crypto-prices/fetch", fetch_crypto_prices),
    path("crypto-prices", crypto_prices),
    path("fund-analysis", fund_analysis),
    path("stock-analysis", stock_analysis),
    path("crypto-analysis", crypto_analysis),
    path("stock-splits", stock_splits),
    path("stock-splits/<uuid:split_id>", stock_split_detail),
    path("fund-chart/<uuid:instrument_id>", fund_chart),
    path("stock-chart/<uuid:instrument_id>", stock_chart),
    path("crypto-chart/<uuid:instrument_id>", crypto_chart),
    path("investment-performance/<str:kind>", investment_performance_view),
    path("fx-rates", fx_rates),
    path("fx-rates/<uuid:rate_id>", fx_rate_detail),
    path("fx-rates/fetch", fetch_fx_rates),
    path("fx-rates/chart", fx_rate_chart),
    path("fx-rates/convert", fx_convert),
]
