from django.urls import path

from . import admin_users, auth, fx_views, privacy, uploads, views
from .analysis_views import crypto_analysis, fund_analysis, portfolio_analysis, stock_analysis
from .instrument_views import crypto_detail, cryptos, fund_detail, funds, stock_detail, stocks
from .market_views import (
    crypto_chart,
    crypto_prices,
    fetch_crypto_prices,
    fetch_fund_prices,
    fetch_stock_prices,
    fund_chart,
    fund_price_detail,
    fund_prices,
    stock_chart,
    stock_price_detail,
    stock_prices,
    stock_split_detail,
    stock_splits,
)
from .overview_views import net_worth_history, summary
from .performance_views import investment_performance_view
from .transaction_views import (
    crypto_orders,
    crypto_transaction_detail,
    fund_transaction_detail,
    orders,
    stock_orders,
    stock_transaction_detail,
)

urlpatterns = [
    path("auth/csrf", auth.csrf),
    path("auth/login", auth.login_view),
    path("auth/logout", auth.logout_view),
    path("auth/me", auth.me),
    path("auth/preferences", auth.update_preferences),
    path("auth/account", auth.update_account),
    path("auth/password", auth.change_password),
    path("auth/password-reset", auth.password_reset_request),
    path("auth/password-reset/confirm", auth.password_reset_confirm),
    path("administration/users", admin_users.users),
    path("administration/users/<uuid:user_id>", admin_users.user_detail),
    path("installation/preferences", auth.update_installation_preferences),
    path("workspaces/current", auth.select_workspace),
    path("workspaces/invitations", auth.invite),
    path("workspaces/invitations/accept", auth.accept_invitation),
    path("account/export", privacy.export_account),
    path("account", privacy.delete_account),
    path("audit-events", privacy.audit_events),
    path("importers", uploads.catalog),
    path("account-imports/<str:kind>/<uuid:account_id>", uploads.upload_for_account),
    path("summary", summary),
    path("net-worth-history", net_worth_history),
    path("savings/accounts", views.savings_accounts),
    path("savings/accounts/<uuid:account_id>", views.savings_account),
    path("savings/history", views.savings_history),
    path(
        "savings/history/<uuid:account_id>/<str:value_date>",
        views.savings_snapshot_detail,
    ),
    path("investments/accounts", views.investment_accounts),
    path("investments/accounts/<uuid:account_id>", views.investment_account),
    path("investments/history", views.investment_history),
    path(
        "investments/history/<uuid:account_id>/<str:value_date>",
        views.investment_snapshot_detail,
    ),
    path("portfolio", views.portfolio),
    path("portfolio/<uuid:asset_id>", views.portfolio_detail),
    path("portfolio-analysis", portfolio_analysis),
    path("real-estate", views.real_estate),
    path("real-estate/<uuid:investment_id>", views.real_estate_detail),
    path("budget", views.budget),
    path("fund-accounts", views.fund_accounts),
    path("fund-accounts/<uuid:account_id>", views.fund_account),
    path("stock-accounts", views.stock_accounts),
    path("stock-accounts/<uuid:account_id>", views.stock_account),
    path("crypto-accounts", views.crypto_accounts),
    path("crypto-accounts/<uuid:account_id>", views.crypto_account),
    path("funds", funds),
    path("funds/<uuid:instrument_id>", fund_detail),
    path("stocks", stocks),
    path("stocks/<uuid:instrument_id>", stock_detail),
    path("cryptos", cryptos),
    path("cryptos/<uuid:instrument_id>", crypto_detail),
    path("orders", orders),
    path("orders/<uuid:transaction_id>", fund_transaction_detail),
    path("fund-orders/upload", uploads.upload_funds),
    path("fund-prices/fetch", fetch_fund_prices),
    path("stock-orders", stock_orders),
    path("stock-orders/upload-tr", uploads.upload_trade_republic),
    path("stock-orders/<uuid:transaction_id>", stock_transaction_detail),
    path("crypto-orders", crypto_orders),
    path("crypto-orders/upload-kraken-pro", uploads.upload_kraken_pro),
    path("crypto-orders/upload-kraken", uploads.upload_kraken_pro),
    path("crypto-orders/<uuid:transaction_id>", crypto_transaction_detail),
    path("fund-prices", fund_prices),
    path("fund-prices/<uuid:instrument_id>", fund_price_detail),
    path("stock-prices/fetch", fetch_stock_prices),
    path("stock-prices", stock_prices),
    path("stock-prices/<uuid:instrument_id>", stock_price_detail),
    path("crypto-prices/fetch", fetch_crypto_prices),
    path("crypto-prices", crypto_prices),
    path("fund-analysis", fund_analysis),
    path("stock-analysis", stock_analysis),
    path("crypto-analysis", crypto_analysis),
    path("stock-splits", stock_splits),
    path("stock-splits/<uuid:split_id>", stock_split_detail),
    path("fund-chart/<uuid:instrument_id>", fund_chart),
    path("stock-chart/<uuid:instrument_id>", stock_chart),
    path("crypto-chart/<uuid:instrument_id>", crypto_chart),
    path("investment-performance/<str:kind>", investment_performance_view),
    path("fx-rates", fx_views.fx_rates),
    path("fx-rates/<uuid:rate_id>", fx_views.fx_rate_detail),
    path("fx-rates/fetch", fx_views.fetch_fx_rates),
    path("fx-rates/chart", fx_views.fx_rate_chart),
    path("fx-rates/convert", fx_views.fx_convert),
]
