from django.urls import path

from . import admin_users, auth, fx_views, privacy, uploads, views

urlpatterns = [
    path("auth/csrf", auth.csrf),
    path("auth/login", auth.login_view),
    path("auth/logout", auth.logout_view),
    path("auth/me", auth.me),
    path("auth/preferences", auth.update_preferences),
    path("auth/account", auth.update_account),
    path("auth/password", auth.change_password),
    path("auth/password-reset", auth.password_reset_request),
    path("auth/password-reset/confirm", auth.password_reset_confirm),
    path("administration/users", admin_users.users),
    path("administration/users/<uuid:user_id>", admin_users.user_detail),
    path("installation/preferences", auth.update_installation_preferences),
    path("workspaces/current", auth.select_workspace),
    path("workspaces/invitations", auth.invite),
    path("workspaces/invitations/accept", auth.accept_invitation),
    path("account/export", privacy.export_account),
    path("account", privacy.delete_account),
    path("audit-events", privacy.audit_events),
    path("importers", uploads.catalog),
    path("account-imports/<str:kind>/<int:legacy_id>", uploads.upload_for_account),
    path("summary", views.summary),
    path("net-worth-history", views.net_worth_history),
    path("savings/accounts", views.savings_accounts),
    path("savings/accounts/<uuid:account_id>", views.savings_account),
    path("savings/history", views.savings_history),
    path(
        "savings/history/<uuid:account_id>/<str:value_date>",
        views.savings_snapshot_detail,
    ),
    path("investments/accounts", views.investment_accounts),
    path("investments/accounts/<uuid:account_id>", views.investment_account),
    path("investments/history", views.investment_history),
    path(
        "investments/history/<uuid:account_id>/<str:value_date>",
        views.investment_snapshot_detail,
    ),
    path("portfolio", views.portfolio),
    path("portfolio/<int:legacy_id>", views.portfolio_detail),
    path("portfolio-analysis", views.portfolio_analysis),
    path("real-estate", views.real_estate),
    path("real-estate/<int:legacy_id>", views.real_estate_detail),
    path("calculator", views.calculator),
    path("calculator/<int:legacy_id>", views.calculator_detail),
    path("budget", views.budget),
    path("fund-accounts", views.fund_accounts),
    path("fund-accounts/<int:legacy_id>", views.fund_account),
    path("stock-accounts", views.stock_accounts),
    path("stock-accounts/<int:legacy_id>", views.stock_account),
    path("crypto-accounts", views.crypto_accounts),
    path("crypto-accounts/<int:legacy_id>", views.crypto_account),
    path("funds", views.funds),
    path("funds/<str:asset_id>", views.fund_detail),
    path("stocks", views.stocks),
    path("stocks/<str:asset_id>", views.stock_detail),
    path("cryptos", views.cryptos),
    path("cryptos/<str:asset_id>", views.crypto_detail),
    path("orders", views.orders),
    path("orders/<str:external_id>", views.transaction_detail),
    path("fund-orders/upload", uploads.upload_funds),
    path("fund-prices/fetch", views.fetch_fund_prices),
    path("stock-orders", views.stock_orders),
    path("stock-orders/upload-tr", uploads.upload_trade_republic),
    path("stock-orders/<str:external_id>", views.transaction_detail),
    path("crypto-orders", views.crypto_orders),
    path("crypto-orders/upload-kraken-pro", uploads.upload_kraken_pro),
    path("crypto-orders/upload-kraken", uploads.upload_kraken_pro),
    path("crypto-orders/<str:external_id>", views.transaction_detail),
    path("fund-prices", views.fund_prices),
    path("fund-prices/<str:asset_id>", views.fund_price_detail),
    path("stock-prices/fetch", views.fetch_stock_prices),
    path("stock-prices", views.stock_prices),
    path("stock-prices/<str:asset_id>", views.stock_price_detail),
    path("crypto-prices/fetch", views.fetch_crypto_prices),
    path("crypto-prices", views.crypto_prices),
    path("fund-analysis", views.fund_analysis),
    path("stock-analysis", views.stock_analysis),
    path("crypto-analysis", views.crypto_analysis),
    path("stock-splits", views.stock_splits),
    path("stock-splits/<str:asset_id>/<str:value_date>", views.stock_split_detail),
    path("fund-chart/<str:asset_id>", views.fund_chart),
    path("stock-chart/<str:asset_id>", views.stock_chart),
    path("crypto-chart/<str:asset_id>", views.crypto_chart),
    path("investment-performance/<str:kind>", views.investment_performance_view),
    path("account-performance", views.account_performance),
    path("fx-rates", fx_views.fx_rates),
    path("fx-rates/<uuid:rate_id>", fx_views.fx_rate_detail),
    path("fx-rates/fetch", fx_views.fetch_fx_rates),
    path("fx-rates/chart", fx_views.fx_rate_chart),
    path("fx-rates/convert", fx_views.fx_convert),
]
