# Generated by Django 5.2.16 on 2026-07-22 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('line_type', models.CharField(max_length=40)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'category'),
            },
        ),
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_label', models.CharField(blank=True, max_length=160)),
                ('name', models.CharField(max_length=160)),
                ('asset_class', models.CharField(max_length=80)),
                ('subtype', models.CharField(blank=True, max_length=120)),
                ('target_weight', models.DecimalField(decimal_places=8, max_digits=12)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_rules', to='accounts.account')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_rules', to='accounts.financialprovider')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
