# Generated by Django 5.2.16 on 2026-07-22 22:02

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrule',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_rules', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='allocationrule',
            constraint=models.CheckConstraint(condition=models.Q(('target_weight__gte', 0), ('target_weight__lte', 1)), name='allocation_weight_between_zero_and_one'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('category'), models.F('workspace'), name='budget_category_ci_unique'),
        ),
    ]
