# Generated by Django 5.2.16 on 2026-07-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_financial_providers'),
        ('planning', '0002_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrule',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='allocationrule',
            constraint=models.UniqueConstraint(fields=('workspace', 'legacy_id'), name='allocation_rule_legacy_id_unique'),
        ),
    ]
