# Generated by Django 5.2.17 on 2026-09-02 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0004_budget_reporting_currency"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AllocationRule",
        ),
    ]
