# Generated by Django 5.2.16 on 2026-07-22 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('warning', 'Advertencia'), ('error', 'Error')], max_length=8)),
                ('code', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=500)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('value_preview', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ('row_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importer_slug', models.CharField(max_length=80)),
                ('source_filename', models.CharField(max_length=255)),
                ('content_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('partial', 'Parcial'), ('failed', 'Fallida'), ('rolled_back', 'Revertida')], default='pending', max_length=16)),
                ('source_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='accounts.account')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
