# Generated by Django 5.2.16 on 2026-07-22 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='importissue',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='imports.importbatch'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['workspace', '-created_at'], name='imports_imp_workspa_8ced66_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['content_sha256', 'importer_slug'], name='imports_imp_content_fc4ab7_idx'),
        ),
    ]
