# Generated by Django 5.2.16 on 2026-08-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='importissue',
            name='severity',
            field=models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], max_length=8),
        ),
    ]
